### ISSUE TITLE
Provide a version compatible with sebastian/exporter 2.x

### ISSUE THREAD

**Issue by cyberwolf** [mikey179/bovigo-assert#6]
We both use this assertion library (in our Behat acceptance tests) and PHPUnit. When trying to upgrade PHPUnit from version 4.x to 5.x, there is a conflict with this package because it requires sebastian/exporter 1.x, while PHPUnit 5.x requires sebastian/exporter 2.x.

**Comment by mikey179** [comment]
I'll look into it. In the meantime you might want to try PHPUnit 5.6, it still requires sebastian/exporter 1.2. PHPUnit 5.7 requires 2.0, and PHPUnit 6.x requires 3.x. I'll look at what can be done here without releasing two new releases just for the sake of preventing version conflicts.

**Comment by mikey179** [comment]
I just released version 2.2.0 which requires sebastian/exporter 2.x.

**Comment by mikey179** [comment]
I also just released version 3.0.0 which is compatible with PHPUnit 6.x and sebastian/exporter 3.x.
